
spring:
  datasource:
    url: jdbc:mysql://mysql_db:3306/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 1
      maximum-pool-size: 10
      connection-timeout: 20000
      idle-timeout: 10000
      connection-test-query: SELECT now();
  flyway:
    locations: classpath:/db/migration
