spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dev_urlshortener
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
